// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(CarDbContext))]
    [Migration("20230301233720_try")]
    partial class @try
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entites.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fuel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Km")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Transmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Kyiv",
                            Fuel = "Gasoline",
                            ImagePath = "https://thumbs.img-sprzedajemy.pl/1000x901c/16/97/24/toyota-camry-hybrid-vi-2006-benzyna-slaskie-560029414.jpg",
                            Km = 300,
                            Name = "Toyota Camry",
                            Price = 7550m,
                            Transmission = "Manual",
                            Year = 2006
                        },
                        new
                        {
                            Id = 2,
                            City = "Dnipro",
                            Fuel = "Diesel",
                            ImagePath = "https://carteam.pl/img/53/53205/4929.jpg",
                            Km = 240,
                            Name = "Renault Megane",
                            Price = 7700m,
                            Transmission = "Manual",
                            Year = 2012
                        },
                        new
                        {
                            Id = 3,
                            City = "Kiyv",
                            Fuel = "Diesel",
                            ImagePath = "https://media.ed.edmunds-media.com/kia/sportage/2017/oem/2017_kia_sportage_4dr-suv_ex_fq_oem_1_1600.jpg",
                            Km = 99,
                            Name = "Kia Sportage",
                            Price = 17500m,
                            Transmission = "Robot",
                            Year = 2017
                        },
                        new
                        {
                            Id = 4,
                            City = "Zhytomyr",
                            Fuel = "Diesel",
                            ImagePath = "https://img.chceauto.pl/audi/q5/audi-q5-suv-3519-32981_head.jpg",
                            Km = 47,
                            Name = "Audi Q5",
                            Price = 59200m,
                            Transmission = "Automat",
                            Year = 2019
                        },
                        new
                        {
                            Id = 5,
                            City = "Uzhhorod",
                            Fuel = "Diesel",
                            ImagePath = "https://i.gaw.to/content/photos/10/97/109744_Porsche_Cayenne_Turbo_S_il_ne_fait_pas_dans_la_dentelle.jpg?460x287",
                            Km = 159,
                            Name = "Porsche Cayenne",
                            Price = 32500m,
                            Transmission = "Automat",
                            Year = 2013
                        },
                        new
                        {
                            Id = 6,
                            City = "Kiyv",
                            Fuel = "Gasoline",
                            ImagePath = "https://e7.pngegg.com/pngimages/968/736/png-clipart-car-ford-focus-electric-2013-ford-focus-2014-ford-focus-se-carrom-compact-car-sedan-thumbnail.png",
                            Km = 218,
                            Name = "Ford Focus",
                            Price = 6900m,
                            Transmission = "Automat",
                            Year = 2013
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
